### ISSUE TITLE
v0 Checklist

### ISSUE THREAD

**Issue by Kroc** [Kroc/v80#3]
## Documentation:
- [x] ReadMe covers all features
- [x] error.txt to elaborate on error meanings
- [x] z80.txt for all mnemonics 
## Processing:
- [x] Conditionals
- [x] 2nd pass!
- [x] Print file/line/col with err
  - [x] decimal numbers! 
- [x] Output file
  - [x] Generate output file-name from input file-name 
- [x] Heap / Stack-overflow checks (open-file, define label/const etc.)
- [X] Hard limit lines to 127 chars
## Expressions:
- [x] Overflow error
- [X] Signed relative offsets (i.e. `jr`)
  - [x] JR is off-by-one
- [x] Parentheses
- [x] Enforce parameter width
- [x] Combined unary operators
## Syntax:
- [x] `.b` bytes
- [x] `.w` words
- [x] `.i` include
- [x] `.a` align
- [x] Shadow registers
- [x] `ld HL, DE` for intent
- [x] Pseudo "v" flag to map "v"/"nv" to "pe"/"po" for clearer intent
- [x] Allow also `hlt` & `hcf` for `halt`
- [x] `sl1` undocumented instruction

## Considered: 
- [ ] Support drive name in CP/M, "A:..."
- [ ] `.s` string?
- [ ] Finalise syntax for v0 -- should const be `#` or UPPERCASE? Should keywords be `.` or something else?
