### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Kroc** [Kroc/v80#5]
- [X] #3 
- [X] #6 

# v1
- [x] Convert code to v80 and self-assemble
- [x] 6502 ISA (assemble 6502 from z80)
- [X] v2 ISA parser / ISA format
- [x] #9
- [ ] #16 
- Notepad++ theme? (depends upon syntax changes)
- Use `cpmtools` to produce disk images for some CP/M machines (e.g. PCW, CPC, Speccy)
- Build option to not use shadow registers (e.g. Zeal 8-bit OS)

# v2
- #2
- eZ80 parser (24-bit)
- SM83 (GameBoy) parser
- Build automation on CP/M (`SUBMIT` / custom exe?)
- Replicate build script on WSL/bash to support Linux out-of-the-box

# v4
- Agon native port (24-bit, not CP/M)

# v?
- Support binary number literals `%...`?
- Parse expressions as part of include file-names (string variables?)
- Z80n from Spectrum Next
- 6809 parser / port? (which systems?)
- 6502 port, "v65", running on c64, Apple2 etc.
- 8086 port, "v86", MS-DOS

**Comment by Kroc** [comment]
Closing as this is a mess and not a good way to plan. I will work on whatever I can; I don't need a million loose ends flapping about
