### ISSUE TITLE
v0.1 Checklist

### ISSUE THREAD

**Issue by Kroc** [Kroc/v80#6]
## Syntax
- [x] Character literal? `'x`
- [x] Decimal numbers?
- [X] Local labels (`_` sigil)
- [x] Binary numbers, `%` sigil
## CP/M
- [x] Disk full error
